language: java
jdk:
- oraclejdk8
script:
  - cd src 
  - if [[ -z "$TRAVIS_TAG" ]]; then PHASE=package; else PHASE=deploy; fi
  - mvn $PHASE --settings .travis.settings.xml
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: kTjGsnPke7zW+UVNAucQwgZa2vhD2IC/GAnKwOxwtUSCUlqmXhsXzaIv7I1WyQ8xSSq+yfKLqJt8bEtF1nn03oKCrvigmyCrLpLHF4h+g059Me8dHLmOHvnT/Mf4kUzULhsiPTGrCQX7T3beKDRHXiK6MwnG9mOYAu7mYwNaC7/jBCadQIHS6R37AN/KrysFVZYcaOR29fq1cCJaxbgNhqCXIARBsMhaoPsySg6F+vcwHF0cx1ldco9AL9UVolZBc6KH+hWkca4K3ku7VJfBjrpMbHwOPVpKBi2BN84ojUY/3Up2VZgb/9F5bk2U2aODKYcyqBCW9CPMP/eCtqZx98VTfGV1yi7wSNVTSsXv31Ox0oDNcssU/OorLEFisCpOQhZQFj45srpLun56vx/N2oBEpmvuY/ooV/s+FiswSF3IqlHaSxXsQiXRpZVSzpJeQuUvTwVszGVkEFoH7YmHhjQ30kJ97XtcFY2mLWYAT++d+Y5josEL9fMyDyDlPPtZEWM9LrRspvER5zjqVFzy4woVO8b07nnD6jWxT/7/qPMRXqTllM0TakUnVBrvXz0QdzBKgf3UBME1pNh6hmqMYdCy894FEW3rWJwV5y+NjeprlRj9ISueXaL0+dlpmotSBJ2V2I2fMw9D8/nIQtvBFuw7YjaIYITuKGq+MpLaATk=
  file_glob: true
  file: "distribution/*/target/*.zip"
  skip_cleanup: true
  on:
    repo: INTER-IoT/gateway
    tags: true
    branches:
      only:
        - master
env:
  global:
    - secure: dSEBdce7bfGHm+VJcoNbxPhzEWvC82ed1eAF3K1eIEARpJQNpx6qSSJThLbqAPl3UGUvH0OTrvtnqMNpY/fnpp/XO2krNpPAcSNxbgm0UElSQhv7r4O9RR5na8+thCip6B/CkJp6pdmFouJwOUot/Qg9jprI5hCW37iq0E0Iijhq/lJdhuM3aFQq8kM69j+oR3ek+Doc6teiIhoFORxUQUzWN8kRrcEMep/stO/ultIoyl9vFxnKniJTf5jzCO98HioLasK4jbPkJGQYFeW+Vz/xMo+c4rVUz1qhcjCdsmVkWx5aDLEeSrt9YEPUv5cBllj/yXFIgvQlDQJWWBcf3L2XnMuEHs9Xq+3MwDn+Ku68ZmFiC8NZ3FRNMInm7qp3TFUqJt1z+l+hgWy+vRWRpvMnmb5ei16petm45vz8s/dGWOpAu0RkietGT7LOCRUJGLfULAQ+0ttPbArilaxTpljYq3Gq0QqKmojmh03HWhyyoUGL6DSLT8aLeizDosvca/naqrc5VpXmYUcKjP/MxUQenv4ATlVWRZ06TzUX4VCrbj3kBsu/oLVa7WoYY2V525uQK65Q8rpEyZspyzp51B9Xn+u4Kbe8oSANgfBxqeVhdpqPTJFSoSYL9g55ezC8GoK8B4IKLT0h88CYeep7kvf5wciLJXiTcy9SQqoyrf0=
    - secure: mRj+1m+nC52ql+81HRJWFKsfLnlzPWnwl8MW9iqJWwIZ+DM7dJE4DjGWXcidMdJh5CYsk2WDVAJGpzIArQ/Y5aVI4GerJtNmy4JO/T28ryWJl6GODlPZrmrMPSMEzvk54ksEucST34DJUEZev62bzaW7Yku2pyZ+3lgT89NTvqnVaHJcUAMZNJiNERTSbcEQlHaHvPUApEEk1PkhitTGdI9nXEvo5AZIJ+lYkgyMEi3EbO33C5DuMw1e4pwG/UG6Kr+6C0Pc1gEzaOQFcNYysvsNDTULzaW+aFgukFquzNo0stGtZ3h/+CKUipAikJEgXO69OhHH3FvfFTjA6wDXMMNjo0U9DVz934r5JncgLUozN5oHP7VE1jo0bzP1IuaK+hYrGCxjNj/lNeiMOvYurdumhKaKZe/CM4nZkLS69qsWqSvJw7s7n8UDDo8uer0aiOgBFmHMxUCfy3wml2x/qwk2pnSj+nXZjfEqsEIlkzBKiroaw3rjXcN7SGdK6TNq+y/b4v3Y3ximpOd71amyKwDxpdiSRIaMbNSz22CiN8bmTWuGVnxcvB4eRxj6K0ywEu3v9dHHATsHFMEep2u4e7VCkhIlbgEP8jlXMBXzbtHgur3stU/5e1+Nx4L0Y+EpjX/Mm3HedON0vkYR2mzg6QLiKHHmfPebwdgGZzPNte4=